baseurl = "https://KengoTeshima.github.io/" # Hostname (and path) to the root.
title = "Kengo Teshima" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
publishdir =  "docs"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Kengo Teshima" # Author's name.
    info = "Data Analyst" # Author's job title or info.
    description = "Kengo Teshima's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "" # Add fixedbar content
    fixedbarContentAfter = "" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    # langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/KengoTeshima/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/ognek4/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/kengo-teshima-755aa2141/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "Qiita"
    # icon = "fab icon-qiita"
    weight = 4
    url = "https://qiita.com/ognek"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "note"
    # icon = "fab icon-note"
    weight = 5
    url = "https://note.com/ognek4"
# [[params.social]]
#    # If icon is not set, Text is displayed.
#    name = "youtube"
#    icon = "fab fa-youtube"
#    weight = 6
#    url = "https://www.youtube.com/playlist?list=PLJ99EoR4L7qpXqnpsdYQrJe_VCxVowkko"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Contents"
    weight = 2
    url = "contents"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Kengo Teshima"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Kengo Teshima"
        info = "Data Analyst"
        description = "Kengo Teshima's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Contents"
        weight = 1.0
        url = "contents"


    [languages.ja]
        languagename = "Japanese"
        title = "手島 健吾"

        [languages.ja.params]
            author = "手島 健吾"
            description = "手島 健吾のサイト"
            keywords = "blog,developer, ブログ, エンジニア, データ分析"
            info = "データアナリスト"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "About"
            weight = 1.0
            url = "about"

            [[languages.ja.menu.main]]
            name = "Contents"
            weight = 2.0
            url = "contents"