baseurl = "https://KengoTeshima.github.io/"
title = "KengoTeshima's Pages"
author = "KengoTeshima"
canonifyurls = true
paginate = 3
theme = "hugo-coder"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"